version: '3.4'

services:
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    ports:
      - 4200:4200
    restart: "always"
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 1024:1024
    restart: always
